services:
  octane:
    container_name: octane-container-dev
    image: octane-container-dev
    build:
      context: ../
      dockerfile: docker/php/Dockerfile.dev
    environment:
      - APP_ROLE=octane
      - PULSE_SERVER_NAME=octane
      - APP_ENV=local
    ports:
      - "80:80"
      - "5173:5173"
      - "8080:8080"
    volumes:
      - ../:/PekeCollection
      - "./octane/php.ini:/usr/local/etc/php/php.ini"
      - "${STORAGE_DIR_PRIVATE:?Error: STORAGE_DIR_PRIVATE is not set}:/PekeCollection/storage/app/private"
    networks:
      - backend
    working_dir: /PekeCollection
    entrypoint: "/entrypoint.sh"

  tus:
    container_name: tus-container
    image: tusproject/tusd:latest
    ports:
      - "1080:1080"
    volumes:
      - "${STORAGE_DIR_PRIVATE:?Error: STORAGE_DIR_PRIVATE is not set}:/private"
    networks:
      - backend
    user: "0:0" # 0:0を明示的に指定しないと、1000:1000にて動作する。ファイル権限エラーになる可能性あり
    command:
      [
        "--port=1080",
        "--hooks-http=http://octane/api/tusd-hooks",
        "--hooks-http-forward-headers=X-CSRF-TOKEN,Cookie",
        "--upload-dir=/private",
        "--base-path=/uploads",
        "--cors-allow-origin=^http:\\/\\/(127\\.0\\.0\\.1|192\\.168\\.11\\.100)$", # カンマ区切りではなく、正規表現で表現が必要
        "--cors-allow-credentials",
        "--cors-allow-headers=X-CSRF-TOKEN"
      ]
    working_dir: /private

networks:
  backend:
    driver: bridge
